### PR TITLE
Expand int types used by protobuf

### LINKED ISSUE #243: The shipper protocol should not convert all numeric values to Float64
The shipper protocol currently uses a fork of the [google.protobuf.Struct ](https://protobuf.dev/reference/protobuf/google.protobuf/#struct), intended to be the protobuf representation of a JSON object. Since JSON does not have a distinct integer or float type, google.protobuf.Struct represents all numeric values as Float64:

https://github.com/elastic/elastic-agent-shipper-client/blob/7610e1852122c0e441800549ab1121aded6e3a06/pkg/helpers/struct.go#LL218-L233C44

```go
	case int:
		return NewNumberValue(float64(newValueTyped)), nil
	case int32:
		return NewNumberValue(float64(newValueTyped)), nil
	case int64:
		return NewNumberValue(float64(newValueTyped)), nil
	case uint:
		return NewNumberValue(float64(newValueTyped)), nil
	case uint32:
		return NewNumberValue(float64(newValueTyped)), nil
	case uint64:
		return NewNumberValue(float64(newValueTyped)), nil
	case float32:
		return NewNumberValue(float64(newValueTyped)), nil
	case float64:
		return NewNumberValue(newValueTyped), nil
```

While this may be technically correct, it introduces a lack of determinism into the number representation from floating point precision errors. We should instead preserve the original numeric type in the shipper protocol rather than strictly attempting to follow the JSON specification. For example, an uint32 should be serialized as a protobuf uint32. See https://protobuf.dev/programming-guides/proto3/#scalar for the full list of scalar protobuf types.

Converting all numeric values to Floats in the shipper protocol creates the opportunity for unexpected behaviour when using processors, specifically conditions. Consider a user of the [Equals](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#condition-equals) condition:

```yaml
equals:
  http.response.code: 200
```

The current shipper protocol would represent `200` as `200.0` internally turning what appears to be an integer or string constant comparison into a floating point comparison with different behaviour.

### PR DESCRIPTION
**Pull request by fearful-symmetry**
Closes https://github.com/elastic/elastic-agent-shipper/issues/243

This expands the numerical types used by the protobuf API, so we're no longer converting random types to `float64`. I just decided to make a separate type for all possible number types, which might be overkill, but it seemed less opaque than just having `float` and `unit` types that might not map to what people expect--and also converting `float32` to `float64` will sometimes result in some unexpected behavior. 

I also made the decision to completely remove the old `double number_value` from the old protobuf definition; I figured we were early enough in the shipper lifetime that we might as well make breaking changes while we can.

This also expands the tests, so we're properly testing `AsInterface` now.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
Oddly enough, the `protoc` output on my dev machine has slightly different output than what's here, not sure if my local `protoc` is outdated, or the formatted copy that's in the repo.

File: pkg/helpers/struct.go [hunk 1]
```diff
@@ -140,18 +139,29 @@ func AsMap(x *messages.Struct) map[string]interface{} {
...
-			case math.IsNaN(v.NumberValue):
-				return "NaN"
-			case math.IsInf(v.NumberValue, +1):
-				return "Infinity"
-			case math.IsInf(v.NumberValue, -1):
-				return "-Infinity"
-			default:
-				return v.NumberValue
-			}
+			return v.Float64Value
```
Comment (ycombinator) [inline pkg/helpers/struct.go:144]: Should the NaN and Infinity cases be added here?

File: api/messages/struct.proto [hunk 2]
```diff
@@ -59,18 +59,28 @@ message Value {
...
+    float float32_value = 3;
+    // Represents an int32 value
+    int32 int32_value = 4;
+    // Represents an int64 value
+    int64 int64_value = 5;
+    // Represents a uint32 value
+    uint32 uint32_value = 6;
+    // Represents a uint64 value
+    uint64 uint64_value = 7;
     // Represents a string value.
```
Comment (faec) [inline api/messages/struct.proto:74]: The idiomatic way to do these kind of changes is to comment the top of the proto with the next unused id, always select from that increasing value when adding fields, and never change the id of old fields or reuse them if deleted. That limits how catastrophic the consequences are if two binaries built against different versions try to talk to each other (there may be unrecognized fields but at least it won't try deserializing raw bytes into the wrong type). We're still prerelease so we have some room to make gratuitous incompatible changes but it's probably still a good habit, and doesn't affect any human-written code.

**Review by faec — APPROVED** [review]

File: pkg/helpers/struct.go (hunk 1 above)
Comment (fearful-symmetry) [reply pkg/helpers/struct.go:144]: So, my thinking was that it doesn't make too much sense for our use case, as most of the time in beats, we wouldn't want a float type quietly converted to a string, as the original code does.

File: api/messages/struct.proto (hunk 2 above)
Comment (fearful-symmetry) [reply api/messages/struct.proto:74]: Yah, my hope was that we're early enough in prerelease that I could get away with not doing that, and keep the values a little "cleaner", for whatever it's worth. Also wasn't sure if it mattered at all, since I needed to remove the original `number` value.

File: pkg/helpers/struct.go (hunk 1 above)
Comment (cmacknz) [reply pkg/helpers/struct.go:144]: In my opinion the strategy we use here should be to pick the format that Elasticsearch accepts, or to let Elasticsearch be the ultimate decision maker on if the data format is acceptable.

ES doesn't look like it accepts NaN and Inf/-Inf values, so the best approach might be to just pass these numbers through as is and let the indexing error tell the user the data is malformed. https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html.

Converting to string here is likely to cause less obvious problems in production if the data destined for a field mapped as double and we tried to write a string value. I agree with not doing that anymore.

Another option is to detect these values in the shipper and not even attempt to index them with an obvious error message. I'm not sure if there is value in doing that here though, we can wait and see how common this problem is in reality and special case it later. It also runs the risk of getting out of sync with what ES accepts in the future.

Comment (ycombinator) [reply pkg/helpers/struct.go:144]: Thank you both.  Makes sense to pass through the value and let the downstream system (try to) handle it.
